### PR TITLE
Make Incidental a property wrapper.

### PR DESCRIPTION
**Pull request by dabrahams**
Unfortunate amount of noise at the declaration site, but uses look better.  What do you think?

### CODE REVIEW

**Review by kyouko-taiga — COMMENTED** [review]
I will cast a _vote blanc_ on this one.

I personally don't like property wrappers. Larger EDSLs aside, I think they only buy marginal benefits at the cost of complexity and "compiler magic". For example, putting myself in the shoes of someone coming from C++ or another language, I think the `@Incidental` wrapper combined with the `private(set)` access level significantly increase the price of the entry ticket to our code base.

Now I need to understand what `@Incidental` does, which is harder and more Swift-specific than when it was a simple generic type. I also need to understand why the property is privately mutable, which I can only figure out if I learn about how property wrappers operate. That's a lot of advanced Swift knowledge for a simple `let` property.

That being said, I agree that the use sites look better, which is also valuable for everyone. So if you think my objections do not outweigh this benefit, you can go ahead.

**Comment by dabrahams** [comment]
> On Dec 13, 2022, at 5:11 AM, Dimi Racordon ***@***.***> wrote:
> 
> I personally don't like property wrappers. Larger EDSLs aside, I think they only buy marginal benefits at the cost of complexity and "compiler magic". For example, putting myself in the shoes of someone coming from C++ or another language, I think the @Incidental wrapper combined with the private(set) access level significantly increase the price of the entry ticket to our code base.
> 
> Now I need to understand what @Incidental does, which is harder and more Swift-specific than when it was a simple generic type. I also need to understand why the property is privately mutable, which I can only figure out if I learn about how property wrappers operate. That's a lot of advanced Swift knowledge for a simple let property.
> 
I agree with your assessment.  The only thing that IMO would justify this change would be if we intended to apply Incidental in many more places than we currently do.  I tried this experiment as a response to your “incidental was making the use sites more complicated” comment.

**Comment by kyouko-taiga** [comment]
> I tried this experiment as a response to your “incidental was making the use sites more complicated” comment.

I thought so. Thanks!

> The only thing that IMO would justify this change would be if we intended to apply Incidental in many more places than we currently do.

Yes, I agree. It could become an idiom in our code base.

I don't think there are that many places where the whole/part relationship doesn't already do the job, though. Looking for all custom equality functions, here are the places where `Incidental` could be added:
- `SourceFile.contents`
- `TypedNode.whole`
- `DoublyLinkedList.address`

We could also use `Incidental` to implement the conformance of `Module` to `Equatable`. But we'll need a custom equality function anyway because the _order_ in which functions appear in `Module.functions` is incidental.

**Comment by dabrahams** [comment]
OK, closing for now.  We always have the experiment for later reference.

**Comment by dabrahams** [comment]
@kyouko-taiga FYI: https://github.com/apple/swift/issues/62543#issuecomment-1347742828

**Pull request closed without merging**
