### PR TITLE
Format check

### PR DESCRIPTION
**Pull request by lucteo**
Add CI check to verify the formatting for the Swift code.

Add script and instructions on how to run swift-format for development.

### CODE REVIEW

**Comment by dabrahams** [comment]
I don't think we can make this a requirement for merge until we have all of Dimitri's editor integrations. Is that done?

**Comment by kyouko-taiga** [comment]
Unfortunately, it seems like the simple approach I knew to integrate formatting tools to Xcode only works with proper Xcode projects, not projects managed with SPM. So AFAIU, our best option would be to create an Xcode extension.

That doesn't seem so hard, but it's work.

**Review by kyouko-taiga — APPROVED** [review]
LGTM

**Comment by lucteo** [comment]
@dabrahams : are you also good with this?

**Comment by dabrahams** [comment]
If Dimi is happy so am ISent from my iPhoneOn Dec 30, 2022, at 9:55 AM, Lucian Radu Teodorescu ***@***.***> wrote:﻿
@dabrahams : are you also good with this?

**Pull request merged**
