### PR TITLE
Add an downcasting initializer to 'TypeProtocol'

### PR DESCRIPTION
**Pull request by kyouko-taiga**

### CODE REVIEW

**Comment by dabrahams** [comment]
Looks like this was a big improvement!

**Comment by kyouko-taiga** [comment]
It was, but it also introduced a very insidious bug by changing the meaning of `MetatypeType.init(_:)`. Took me a good hour to find it.

Should be fine for new code though.

**Comment by dabrahams** [comment]
The way you avoid that problem is to first make a commit changing the signature of `MetatypeType.init()`, get that to compile, then add your new initializer.

**Comment by kyouko-taiga** [comment]
That's what I did, and then I got bitten by a merge 😅

**Pull request merged**
